version: "3"
services:
    app:
        image: nginx:1.23.3-alpine-slim
        ports:
            - 8082:80
        volumes:
        - ./app:/usr/share/nginx/html:z
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        container_name: salon-admin
